nodeLinker: node-modules

supportedArchitectures:
  os: [linux, darwin]
  cpu: [x64, arm64]
  libc: [glibc]

packageExtensions:
  remix-keycloak@*:
    peerDependencies:
      "@remix-run/react": "^2.17.0"