apiVersion: apps/v1
kind: Deployment
metadata:
  name: firecrest-web-ui-depl
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: firecrest-web-ui
  template:
    metadata:
      labels:
        app: firecrest-web-ui
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
        co.elastic.logs/processors.1.add_fields.target: "app.environment"
        co.elastic.logs/processors.1.add_fields.fields.name: {{ .Values.global.environment }}
        co.elastic.logs/processors.2.add_fields.target: "app.version"
        co.elastic.logs/processors.2.add_fields.fields.name: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: firecrest-web-ui
          image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
          env:
            - name: SERVICE_NAME
              value: "firecrest-web-ui"
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: UI_HOSTNAME
              value: {{ .Values.global.dns.webUI }}
            - name: APP_VERSION
              value: {{ .Chart.AppVersion }}
            - name: LOGGING_LEVEL
              value: {{ .Values.loggingLevel }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: firecrest-web-ui-v2
                  key: session-secret
            - name: FILE_UPLOAD_LIMIT
              value: {{ .Values.fileUploadLimit | quote }}
            - name: KEYCLOAK_DOMAIN
              value: {{ .Values.keycloakDomain }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloakRealm }}
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: firecrest-web-ui-v2
                  key: keycloak-client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: firecrest-web-ui-v2
                  key: keycloak-client-secret
            - name: KEYCLOAK_CALLBACK_URL
              value: {{ .Values.keycloakCallbackUrl }}
            - name: KEYCLOAK_LOGOUT_REDIRECT_URL
              value: {{ .Values.keycloakLogoutRedirectUrl }}
            - name: FIRECREST_API_BASE_URL
              value: {{ .Values.firecrestApiBaseUrl }}
            - name: SENTRY_ACTIVE
              value: {{ .Values.sentryActive | quote }}
            - name: SENTRY_DEBUG
              value: {{ .Values.sentryDebug | quote }}
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: {{ .Values.sentryTracesSampleRate | quote }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: firecrest-web-ui-v2
                  key: sentry-dsn
            - name: SENTRY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: firecrest-web-ui-v2
                  key: sentry-auth-token
            - name: REDIS_ACTIVE
              value: {{ .Values.redisActive | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redisHost }}
            - name: REDIS_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firecrest-web-ui-v2
                  key: redis-auth-password
            - name: SUPPORT_URL
              value: {{ .Values.supportUrl }}
            - name: DOC_URL
              value: {{ .Values.docUrl }}
            - name: REPO_URL
              value: {{ .Values.repoUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: firecrest-web-ui-srv
spec:
  selector:
    app: firecrest-web-ui
  ports:
    - name: firecrest-web-ui
      protocol: TCP
      port: 3000
      targetPort: 3000
