name: Build Docs

on:
  release:
    types: [released]

jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    env:
      GH_PAGES_BRANCH: gh-pages
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checks out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Configure Git User
        run: |
          echo "Configured user to '$GITHUB_ACTOR'"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Build MkDocs
        run: |
          pip install --upgrade pip
          pip install -r ./docs/requirements.txt
          rm -rf site .site
          mkdocs build
          mv site .site
      - name: Merge site with gh-pages branch
        run: |
          git fetch origin $GH_PAGES_BRANCH:$GH_PAGES_BRANCH
          git checkout $GH_PAGES_BRANCH
          [ -d charts ] && mv charts .charts || echo "No charts directory to preserve"
          find . -mindepth 1 -maxdepth 1 ! -name '.*' ! -name '.git' -exec rm -rf {} \;
          mv  ./.site/* ./
          rm -rf .site
          [ -d .charts ] && mv .charts charts || echo "No charts directory to restore"
      - name: Check for changes
        run: |
          git diff --quiet || echo "CHANGES=true" >> $GITHUB_ENV
      - name: Publish MkDocs
        if: ${{ env.CHANGES == 'true' }}
        run: |
          git add .
          git commit -m "New documentation release (${{ github.ref_name }})"
          git push -u origin $GH_PAGES_BRANCH
