name: FirecREST UI CI/CD Workflow

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  release:
    types: [prereleased, released]

env:
  RELEASE_VERSION: ${{ github.ref_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CHART_DIR: deploy/helm
  GH_PAGES_BRANCH: gh-pages
  VENV_CACHE_DIR: ${{ github.workspace }}/venv/

jobs:
  static_code_analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Corepack for Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Run audit
        run: yarn npm audit
        continue-on-error: true

      - name: Allow failure (audit)
        if: failure()
        run: echo "Audit failed but continuing"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Corepack for Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Run tests
        run: yarn run test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Corepack for Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Run linter
        run: yarn run lint

      - name: Allow failure (lint)
        if: failure()
        run: echo "Lint failed but continuing"

      - name: Check the license headers
        run: yarn run check-licence

  helm-lint:
    name: Helm Chart Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm (v3.14.3)
        uses: azure/setup-helm@v3
        with:
          version: v3.14.3

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Helm Lint
        run: helm lint ./deploy/helm/firecrest-web-ui

      - name: Template Rendering and Validation
        run: |
          helm template firecrest-ui-ci ./deploy/helm/firecrest-web-ui \
            --namespace firecrest-ui-ci \
            --kube-version 1.29 \
            --values ./deploy/helm/firecrest-web-ui/values.yaml \
            --debug --dry-run > rendered.yaml

          yamllint rendered.yaml
