name: firecrest-ui QA

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  VENV_CACHE_DIR: ${{ github.workspace }}/venv/

jobs:
  static_code_analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run audit
        run: yarn run audit
      - name: Allow failure (audit)
        if: failure()
        run: echo "Audit failed but continuing"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn run lint
      - name: Allow failure (lint)
        if: failure()
        run: echo "Lint failed but continuing"
